name: Unit test

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Init node env
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: yarn
      - run: yarn test
        env:
          CI: true
