name: Unit test

on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        typeorm-version: ['0.3.0', '0.3.20', 'latest']
    steps:
      - uses: actions/checkout@v4
      - name: Init node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn add -D typeorm@${{ matrix.typeorm-version }}
      - run: yarn test
        env:
          CI: true
